### PR TITLE
Blog post on obtaining leaf temperature estimats

### PR DESCRIPTION
**Pull request by PaulMelloy**
It could do with a better title if you would like to change

### CODE REVIEW

**Comment by PaulMelloy** [comment]
@adamhsparks @emdelponte , let me know if you need me to do anything else here

**Comment by adamhsparks** [comment]
OK, thanks. Haven’t had a chance to look at it yet.

**Comment by adamhsparks** [comment]
Hi Paul, I've made several editorial changes including adding logos for the packages, properly citing the _nasapower_ package and spelling and punctuation checks.

Let me know if you're OK with the changes and I'll merge and publish.

**Comment by adamhsparks** [comment]
I'll deal with the conflicts locally, don't worry about that. Just check your article, please.

**Comment by PaulMelloy** [comment]
Hi Adam,
I am not sure how to view these changes but they sound all good to me :)

**Comment by adamhsparks** [comment]
https://github.com/openplantpathology/OpenPlantPathology/tree/PaulMelloy-master

**Pull request merged**
