### PR TITLE
To add tag and link external URL

### PR DESCRIPTION
**Pull request by sporangia**
Updating profile

### CODE REVIEW

**Comment by adamhsparks** [comment]
Looks good. The failed checks are from before your PR. I think I can merge it successfully.

**Comment by adamhsparks** [comment]
Well, I missed an issue with your PR, but have it all fixed now.  Thanks for updating!

**Review by adamhsparks — COMMENTED** [review]
Missing " around external link.

I missed this too in my initial review but have corrected it post merge.

**Comment by sporangia** [comment]
Is that why it failed the checks?  I couldn't figure that out.

**Pull request merged**
